In [2]:
import numpy as np

In [4]:
data = [1, 2, 3, 4, 5]
arr = np.array(data) #создать из list

print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)



[1 2 3 4 5]
(5,)
int64
1


In [5]:
arr4 = np.arange(1, 5, 0.5) #от 1 до 5 с шагом 0,5
arr4

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [6]:
arr5 = np.linspace(0, 2, 30) #заполнить от 0 до 2 30ю элементами
arr5

array([0.        , 0.06896552, 0.13793103, 0.20689655, 0.27586207,
       0.34482759, 0.4137931 , 0.48275862, 0.55172414, 0.62068966,
       0.68965517, 0.75862069, 0.82758621, 0.89655172, 0.96551724,
       1.03448276, 1.10344828, 1.17241379, 1.24137931, 1.31034483,
       1.37931034, 1.44827586, 1.51724138, 1.5862069 , 1.65517241,
       1.72413793, 1.79310345, 1.86206897, 1.93103448, 2.        ])

In [7]:
random_arr = np.random.random((5,)) #заполнить рандомными элем
random_arr

array([0.64431241, 0.40860893, 0.55635878, 0.93209644, 0.95813833])

In [8]:
random_arr2 = (10 - -5)*np.random.random_sample((5,)) - 5 #5 чисел от 10 до -5
random_arr2

array([ 2.67422128,  7.62937298,  1.67444622,  7.43205601, -2.09961061])