In [2]:
import numpy as np

In [4]:
data = [1, 2, 3, 4, 5]
arr = np.array(data) #создать из list

print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)



[1 2 3 4 5]
(5,)
int64
1


In [5]:
arr4 = np.arange(1, 5, 0.5) #от 1 до 5 с шагом 0,5
arr4

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [6]:
arr5 = np.linspace(0, 2, 30) #заполнить от 0 до 2 30ю элементами
arr5

array([0.        , 0.06896552, 0.13793103, 0.20689655, 0.27586207,
       0.34482759, 0.4137931 , 0.48275862, 0.55172414, 0.62068966,
       0.68965517, 0.75862069, 0.82758621, 0.89655172, 0.96551724,
       1.03448276, 1.10344828, 1.17241379, 1.24137931, 1.31034483,
       1.37931034, 1.44827586, 1.51724138, 1.5862069 , 1.65517241,
       1.72413793, 1.79310345, 1.86206897, 1.93103448, 2.        ])

In [7]:
random_arr = np.random.random((5,)) #заполнить рандомными элем
random_arr

array([0.64431241, 0.40860893, 0.55635878, 0.93209644, 0.95813833])

In [8]:
random_arr2 = (10 - -5)*np.random.random_sample((5,)) - 5 #5 чисел от 10 до -5
random_arr2

array([ 2.67422128,  7.62937298,  1.67444622,  7.43205601, -2.09961061])

In [9]:
matrix = np.array([(1, 2, 3),(4, 5, 6)], dtype = np.float64)
matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [12]:
matrix2 = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)]) #3х мерная матрица
print(matrix2)
print(matrix2.shape)
print(matrix2.dtype)
print(matrix2.ndim)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int64
2


In [15]:
matrix2.reshape(1,9)
matrix.reshape(3,2)  #изменить форму

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [17]:
print(matrix2) 
matrix2=np.resize(matrix,(2,2)) #обрезать матрицу на 4х элем
print()
print(matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1. 2.]
 [3. 4.]]


In [19]:
matrix3 = np.arange(16).reshape(2,8) #сгенерировать 16 элем и сделать из них матрицу 2 на 8
matrix3

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [22]:
np.zeros((3,4)) #матрица из нулей

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((2,2)) #матрица из 1

array([[1., 1.],
       [1., 1.]])

In [24]:
np.eye(5) #единичная матрица порядка 5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.full((3,3),9) #матрица размера 3 на 3, заполненная 9

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [30]:
np.empty((3,2)) #создать пустую матрицу 3 на 2

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [34]:
matrix11=np.array([(1,2), (3,4)])
print(matrix11)
print()
matrix12=np.array([(5,6),(7,8)])
print(matrix12)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [35]:
matrix4 = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
matrix4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.delete(matrix4, 1,axis=0) #удалить 1(2) строку матрицы

array([[1, 2, 3],
       [7, 8, 9]])

In [39]:
np.delete(matrix4, 2, axis=1) #удалить 2(3) столбец

array([[1, 2],
       [4, 5],
       [7, 8]])

In [46]:
arr1=np.array([(1,2), (3,4)])
print(arr1)
print()
arr2=np.array([(5,6),(7,8)])
print(arr2)
print()
arr = np.concatenate((arr1, arr2), axis=1) #добавить как столбцы
arr

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]



array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [47]:
np.hstack((arr1,arr2)) #горизонтальное соединение


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [48]:
np.vstack((arr1,arr2)) #вертикальное соединение

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Индексация

In [49]:
matrix = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
matrix[1,2] #2(3) элемент 1(2) строки

6

In [51]:
matrix[2] #2(3 строка)

array([7, 8, 9])

In [52]:
matrix[:,2] #2(3) столбец

array([3, 6, 9])

In [61]:
matrix[1:3,0:2] #1 и 2 столбцы, 0 и 1 строки

array([[4, 5],
       [7, 8]])

Специальные операции

In [62]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
matrix.T #транспонировать

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [64]:
matrix.flatten() #в массив

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.linalg.inv(matrix) #обратная матрица

LinAlgError: ignored